export default function HomePage() {
  return (
    <div className="flex flex-col">
      <div>ALOOOOOOOOOOOO</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
      <div>HEJ</div>
    </div>
  );
}
